FROM svizor/zoomcamp-model:3.10.12-slim

RUN pip install pipenv

WORKDIR /app 

COPY ["Pipfile","Pipfile.lock","./"]

RUN pipenv install --system --deploy

#COPY ["dv.bin","model1.bin","score.py","./"]

COPY ["score.py","./"]

EXPOSE 9697

ENTRYPOINT ["gunicorn","--bind=0.0.0.0:9697","score:app" ]

